/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ivaneh' at '10.04.16 19:28' with Gradle 2.11
 *
 * @author ivaneh, @date 10.04.16 19:28
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
